// flow-typed signature: 412f9f98091074fed937301b8ea9abd4
// flow-typed version: <<STUB>>/react-native-textinput-effects_v^0.4.2/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-textinput-effects'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-textinput-effects' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-textinput-effects/lib/Akira' {
  declare module.exports: any;
}

declare module 'react-native-textinput-effects/lib/BaseInput' {
  declare module.exports: any;
}

declare module 'react-native-textinput-effects/lib/Fumi' {
  declare module.exports: any;
}

declare module 'react-native-textinput-effects/lib/Hideo' {
  declare module.exports: any;
}

declare module 'react-native-textinput-effects/lib/Hoshi' {
  declare module.exports: any;
}

declare module 'react-native-textinput-effects/lib/index' {
  declare module.exports: any;
}

declare module 'react-native-textinput-effects/lib/Isao' {
  declare module.exports: any;
}

declare module 'react-native-textinput-effects/lib/Jiro' {
  declare module.exports: any;
}

declare module 'react-native-textinput-effects/lib/Kaede' {
  declare module.exports: any;
}

declare module 'react-native-textinput-effects/lib/Kohana' {
  declare module.exports: any;
}

declare module 'react-native-textinput-effects/lib/Madoka' {
  declare module.exports: any;
}

declare module 'react-native-textinput-effects/lib/Makiko' {
  declare module.exports: any;
}

declare module 'react-native-textinput-effects/lib/Sae' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-textinput-effects/lib/Akira.js' {
  declare module.exports: $Exports<'react-native-textinput-effects/lib/Akira'>;
}
declare module 'react-native-textinput-effects/lib/BaseInput.js' {
  declare module.exports: $Exports<'react-native-textinput-effects/lib/BaseInput'>;
}
declare module 'react-native-textinput-effects/lib/Fumi.js' {
  declare module.exports: $Exports<'react-native-textinput-effects/lib/Fumi'>;
}
declare module 'react-native-textinput-effects/lib/Hideo.js' {
  declare module.exports: $Exports<'react-native-textinput-effects/lib/Hideo'>;
}
declare module 'react-native-textinput-effects/lib/Hoshi.js' {
  declare module.exports: $Exports<'react-native-textinput-effects/lib/Hoshi'>;
}
declare module 'react-native-textinput-effects/lib/index.js' {
  declare module.exports: $Exports<'react-native-textinput-effects/lib/index'>;
}
declare module 'react-native-textinput-effects/lib/Isao.js' {
  declare module.exports: $Exports<'react-native-textinput-effects/lib/Isao'>;
}
declare module 'react-native-textinput-effects/lib/Jiro.js' {
  declare module.exports: $Exports<'react-native-textinput-effects/lib/Jiro'>;
}
declare module 'react-native-textinput-effects/lib/Kaede.js' {
  declare module.exports: $Exports<'react-native-textinput-effects/lib/Kaede'>;
}
declare module 'react-native-textinput-effects/lib/Kohana.js' {
  declare module.exports: $Exports<'react-native-textinput-effects/lib/Kohana'>;
}
declare module 'react-native-textinput-effects/lib/Madoka.js' {
  declare module.exports: $Exports<'react-native-textinput-effects/lib/Madoka'>;
}
declare module 'react-native-textinput-effects/lib/Makiko.js' {
  declare module.exports: $Exports<'react-native-textinput-effects/lib/Makiko'>;
}
declare module 'react-native-textinput-effects/lib/Sae.js' {
  declare module.exports: $Exports<'react-native-textinput-effects/lib/Sae'>;
}
