// flow-typed signature: 813e1417556e56d684598620f909bfbe
// flow-typed version: <<STUB>>/react-native-toast-native_v^1.2.1/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-toast-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-toast-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-toast-native/index' {
  declare module.exports: $Exports<'react-native-toast-native'>;
}
declare module 'react-native-toast-native/index.js' {
  declare module.exports: $Exports<'react-native-toast-native'>;
}
