// flow-typed signature: 1d0b24712c1fff52e3207af7e2de7819
// flow-typed version: <<STUB>>/react-native-config_v^0.11.5/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-config/index' {
  declare module.exports: $Exports<'react-native-config'>;
}
declare module 'react-native-config/index.js' {
  declare module.exports: $Exports<'react-native-config'>;
}
