# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EatItRight' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EatItRight
  pod 'Firebase/Core'

  target 'EatItRightTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'EatItRight-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EatItRight-tvOS

  target 'EatItRight-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
